_target_: src.models.ImageFlowModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.net.MegaUNet2DModel
  k: 768  # 3 * 256
  dim: 32  # is square root
  groups_norm: 32
  filters: 512
  activation: swish

compile: false
