_target_: src.models.SFMModule

# Net params
net:
  _target_: src.models.net.GraphTransformer
  n_layers: 5
  input_dims: {'X': 40, 'E': 10, 'y': 12}
  hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}
  hidden_dims: {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}
  output_dims: {'X': 17, 'E': 5, 'y': 0}
  act_fn_in: relu
  act_fn_out: relu
  addition: True

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  amsgrad: true

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# extra_features: all
# extra_molecular_features: false
# use_context: True

compile: false