_target_: src.models.SFMModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 1000
  eta_min: 0.00008

net:
  _target_: src.models.net.TMLPSignal
  activation: swish
  hidden: 512
  depth: 8
  fourier: null


compile: false
